### ISSUE TITLE
where the method addTemplatedParam in SpringMvcContract?

### ISSUE THREAD

**Issue by farsunset** [spring-cloud/spring-cloud-openfeign#87]
spring-cloud-starter-openfeign 2.0.2.RELEASE
io.github.openfeign 10.1.0
springboot 2.1.0

Feign Client

@FeignClient(name = "manager-service",url = "${spring.api.application.url}")
public interface ILoanApplicationRemoteService {

    @PostMapping(value = "/autoReject/v1",produces = "application/json")
    ManagerResponse reject(@RequestHeader(name = "X-Auth-Token") String token);

    @PostMapping(value = "/autoApprove/v1",produces = "application/json")
    ManagerResponse approve(@RequestHeader(name = "X-Auth-Token") String token);

}

has RequestHeader ,start springboot has an Error 

Description:

An attempt was made to call the method org.springframework.cloud.openfeign.support.SpringMvcContract.addTemplatedParam(Ljava/util/Collection;Ljava/lang/String;)Ljava/util/Collection; but it does not exist. Its class, org.springframework.cloud.openfeign.support.SpringMvcContract, is available from the following locations:

    jar:file:/C:/Users/Administrator/.m2/repository/org/springframework/cloud/spring-cloud-openfeign-core/2.0.2.RELEASE/spring-cloud-openfeign-core-2.0.2.RELEASE.jar!/org/springframework/cloud/openfeign/support/SpringMvcContract.class

It was loaded from the following location:

    file:/C:/Users/Administrator/.m2/repository/org/springframework/cloud/spring-cloud-openfeign-core/2.0.2.RELEASE/spring-cloud-openfeign-core-2.0.2.RELEASE.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.cloud.openfeign.support.SpringMvcContract

**Comment by ryanjbaxter** [comment]
Spring Cloud Finchley is not compatible with Boot 2.1.0.  If you want to use Boot 2.1.0 you need to use Greenwich.M3.

**Comment by farsunset** [comment]
> Spring Cloud Finchley is not compatible with Boot 2.1.0. If you want to use Boot 2.1.0 you need to use Greenwich.M3.

thinks~ bug i fixed this error like this

**Comment by Ravis22** [comment]
Same issue for version 2.0.1.RELEASE
java.lang.NoSuchMethodError: org.springframework.cloud.openfeign.support.SpringMvcContract.addTemplatedParam(Ljava/util/Collection;Ljava/lang/String;)Ljava/util/Collection;

**Comment by OlgaMaciaszek** [comment]
Hello @farsunset  @Ravis22 . The OpenFeign 10.1.0 support was introduced in spring-cloud-openfeign 2.1.0. Will not work with 2.0.x. You should use Greenwich with boot 2.1.0 to use OF 10.1.0.
